"""create mata kuliah table

Revision ID: 41455bc528dc
Revises: b9ef5f487374
Create Date: 2025-05-08 17:50:01.366648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41455bc528dc'
down_revision = 'b9ef5f487374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matakuliah', 'kode_mk',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matakuliah', 'kode_mk',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
